version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/srv/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    build:
      context: ./docker/php
    ports:
      - 9090:9000
    volumes:
      - ./:/srv/www/api
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - code-network
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mysql:
    image: mysql:5.7
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}

networks:
  code-network:
    driver: bridge